//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Calibration : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Calibration(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Calibration obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Calibration obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Calibration() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_Calibration(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool calibrated {
    set {
      nrc_interfacePINVOKE.Calibration_calibrated_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.Calibration_calibrated_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_CalibrationPoint_t point {
    set {
      nrc_interfacePINVOKE.Calibration_point_set(swigCPtr, SWIGTYPE_p_std__vectorT_CalibrationPoint_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.Calibration_point_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_CalibrationPoint_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_CalibrationPoint_t(cPtr, false);
      return ret;
    } 
  }

  public int point_num {
    set {
      nrc_interfacePINVOKE.Calibration_point_num_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Calibration_point_num_get(swigCPtr);
      return ret;
    } 
  }

  public void addCalibrationPoint(CalibrationPoint pos) {
    nrc_interfacePINVOKE.Calibration_addCalibrationPoint(swigCPtr, CalibrationPoint.getCPtr(pos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public CalibrationPoint getPoint(int index) {
    CalibrationPoint ret = new CalibrationPoint(nrc_interfacePINVOKE.Calibration_getPoint(swigCPtr, index), true);
    return ret;
  }

  public Calibration(int num_points) : this(nrc_interfacePINVOKE.new_Calibration__SWIG_0(num_points), true) {
  }

  public Calibration() : this(nrc_interfacePINVOKE.new_Calibration__SWIG_1(), true) {
  }

}
