//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CollisionPara : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CollisionPara(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CollisionPara obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CollisionPara obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CollisionPara() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_CollisionPara(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorDouble collisionDetection_run {
    set {
      nrc_interfacePINVOKE.CollisionPara_collisionDetection_run_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.CollisionPara_collisionDetection_run_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public VectorDouble collisionDetection_teach {
    set {
      nrc_interfacePINVOKE.CollisionPara_collisionDetection_teach_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.CollisionPara_collisionDetection_teach_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public double position_delay_time_ms_value {
    set {
      nrc_interfacePINVOKE.CollisionPara_position_delay_time_ms_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.CollisionPara_position_delay_time_ms_value_get(swigCPtr);
      return ret;
    } 
  }

  public double error_enable_time_ms_value {
    set {
      nrc_interfacePINVOKE.CollisionPara_error_enable_time_ms_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.CollisionPara_error_enable_time_ms_value_get(swigCPtr);
      return ret;
    } 
  }

  public uint axisum {
    set {
      nrc_interfacePINVOKE.CollisionPara_axisum_set(swigCPtr, value);
    } 
    get {
      uint ret = nrc_interfacePINVOKE.CollisionPara_axisum_get(swigCPtr);
      return ret;
    } 
  }

  public CollisionPara() : this(nrc_interfacePINVOKE.new_CollisionPara(), true) {
  }

}
