//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ConveyorSensorParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConveyorSensorParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConveyorSensorParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConveyorSensorParams obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConveyorSensorParams() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ConveyorSensorParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int conveyorID {
    set {
      nrc_interfacePINVOKE.ConveyorSensorParams_conveyorID_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorSensorParams_conveyorID_get(swigCPtr);
      return ret;
    } 
  }

  public double sensorPosDeg_A {
    set {
      nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_A_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_A_get(swigCPtr);
      return ret;
    } 
  }

  public double sensorPosDeg_B {
    set {
      nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_B_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_B_get(swigCPtr);
      return ret;
    } 
  }

  public double sensorPosDeg_C {
    set {
      nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_C_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_C_get(swigCPtr);
      return ret;
    } 
  }

  public double sensorPosDeg_X {
    set {
      nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_X_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_X_get(swigCPtr);
      return ret;
    } 
  }

  public double sensorPosDeg_Y {
    set {
      nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_Y_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_Y_get(swigCPtr);
      return ret;
    } 
  }

  public double sensorPosDeg_Z {
    set {
      nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_Z_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorSensorParams_sensorPosDeg_Z_get(swigCPtr);
      return ret;
    } 
  }

  public ConveyorSensorParams() : this(nrc_interfacePINVOKE.new_ConveyorSensorParams(), true) {
  }

}
