//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ConveyorBasicParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConveyorBasicParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConveyorBasicParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConveyorBasicParams obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConveyorBasicParams() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ConveyorBasicParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int conveyorID {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_conveyorID_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorBasicParams_conveyorID_get(swigCPtr);
      return ret;
    } 
  }

  public double compensation_encoderVal {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_compensation_encoderVal_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorBasicParams_compensation_encoderVal_get(swigCPtr);
      return ret;
    } 
  }

  public double compensation_time {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_compensation_time_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorBasicParams_compensation_time_get(swigCPtr);
      return ret;
    } 
  }

  public int conveyor_encoderDirection {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_encoderDirection_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_encoderDirection_get(swigCPtr);
      return ret;
    } 
  }

  public double conveyor_encoderResolution {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_encoderResolution_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_encoderResolution_get(swigCPtr);
      return ret;
    } 
  }

  public double conveyor_encoderValue {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_encoderValue_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_encoderValue_get(swigCPtr);
      return ret;
    } 
  }

  public double conveyor_maxEncoderVal {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_maxEncoderVal_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_maxEncoderVal_get(swigCPtr);
      return ret;
    } 
  }

  public double conveyor_minEncoderVal {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_minEncoderVal_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_minEncoderVal_get(swigCPtr);
      return ret;
    } 
  }

  public int conveyor_posRecordMode {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_posRecordMode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_posRecordMode_get(swigCPtr);
      return ret;
    } 
  }

  public double conveyor_speed {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_speed_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_speed_get(swigCPtr);
      return ret;
    } 
  }

  public int conveyor_userCoord {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_userCoord_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorBasicParams_conveyor_userCoord_get(swigCPtr);
      return ret;
    } 
  }

  public int track_height {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_track_height_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorBasicParams_track_height_get(swigCPtr);
      return ret;
    } 
  }

  public int track_on_run_mode_with_target_overrun {
    set {
      nrc_interfacePINVOKE.ConveyorBasicParams_track_on_run_mode_with_target_overrun_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorBasicParams_track_on_run_mode_with_target_overrun_get(swigCPtr);
      return ret;
    } 
  }

  public ConveyorBasicParams() : this(nrc_interfacePINVOKE.new_ConveyorBasicParams(), true) {
  }

}
