//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IOtype : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IOtype(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IOtype obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IOtype obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IOtype() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_IOtype(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int num {
    set {
      nrc_interfacePINVOKE.IOtype_num_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IOtype_num_get(swigCPtr);
      return ret;
    } 
  }

  public VectorString type {
    set {
      nrc_interfacePINVOKE.IOtype_type_set(swigCPtr, VectorString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.IOtype_type_get(swigCPtr);
      VectorString ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorString(cPtr, false);
      return ret;
    } 
  }

  public VectorVectorInt io_port_sum {
    set {
      nrc_interfacePINVOKE.IOtype_io_port_sum_set(swigCPtr, VectorVectorInt.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.IOtype_io_port_sum_get(swigCPtr);
      VectorVectorInt ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorInt(cPtr, false);
      return ret;
    } 
  }

  public IOtype() : this(nrc_interfacePINVOKE.new_IOtype(), true) {
  }

}
