//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ModbusRTUParameter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ModbusRTUParameter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ModbusRTUParameter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ModbusRTUParameter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ModbusRTUParameter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ModbusRTUParameter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int slaveId {
    set {
      nrc_interfacePINVOKE.ModbusRTUParameter_slaveId_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ModbusRTUParameter_slaveId_get(swigCPtr);
      return ret;
    } 
  }

  public int port {
    set {
      nrc_interfacePINVOKE.ModbusRTUParameter_port_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ModbusRTUParameter_port_get(swigCPtr);
      return ret;
    } 
  }

  public int baudrate {
    set {
      nrc_interfacePINVOKE.ModbusRTUParameter_baudrate_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ModbusRTUParameter_baudrate_get(swigCPtr);
      return ret;
    } 
  }

  public string checkBit {
    set {
      nrc_interfacePINVOKE.ModbusRTUParameter_checkBit_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.ModbusRTUParameter_checkBit_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int dataBit {
    set {
      nrc_interfacePINVOKE.ModbusRTUParameter_dataBit_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ModbusRTUParameter_dataBit_get(swigCPtr);
      return ret;
    } 
  }

  public int stopBit {
    set {
      nrc_interfacePINVOKE.ModbusRTUParameter_stopBit_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ModbusRTUParameter_stopBit_get(swigCPtr);
      return ret;
    } 
  }

  public ModbusRTUParameter() : this(nrc_interfacePINVOKE.new_ModbusRTUParameter(), true) {
  }

}
