//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum PosType {
  data = 0,
  PType = 1,
  E_TYPE = 2,
  RP_TYPE = 3,
  AP_TYPE = 4,
  GPType = 5,
  GEType = 6
}
