//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RemoteControl : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RemoteControl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RemoteControl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RemoteControl obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RemoteControl() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_RemoteControl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int clearStashPort {
    set {
      nrc_interfacePINVOKE.RemoteControl_clearStashPort_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_clearStashPort_get(swigCPtr);
      return ret;
    } 
  }

  public int faultResetPort {
    set {
      nrc_interfacePINVOKE.RemoteControl_faultResetPort_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_faultResetPort_get(swigCPtr);
      return ret;
    } 
  }

  public int pausePort {
    set {
      nrc_interfacePINVOKE.RemoteControl_pausePort_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_pausePort_get(swigCPtr);
      return ret;
    } 
  }

  public int startPort {
    set {
      nrc_interfacePINVOKE.RemoteControl_startPort_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_startPort_get(swigCPtr);
      return ret;
    } 
  }

  public int stopPort {
    set {
      nrc_interfacePINVOKE.RemoteControl_stopPort_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_stopPort_get(swigCPtr);
      return ret;
    } 
  }

  public int clearStashValue {
    set {
      nrc_interfacePINVOKE.RemoteControl_clearStashValue_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_clearStashValue_get(swigCPtr);
      return ret;
    } 
  }

  public int faultResetValue {
    set {
      nrc_interfacePINVOKE.RemoteControl_faultResetValue_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_faultResetValue_get(swigCPtr);
      return ret;
    } 
  }

  public int pauseValue {
    set {
      nrc_interfacePINVOKE.RemoteControl_pauseValue_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_pauseValue_get(swigCPtr);
      return ret;
    } 
  }

  public int startValue {
    set {
      nrc_interfacePINVOKE.RemoteControl_startValue_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_startValue_get(swigCPtr);
      return ret;
    } 
  }

  public int stopValue {
    set {
      nrc_interfacePINVOKE.RemoteControl_stopValue_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RemoteControl_stopValue_get(swigCPtr);
      return ret;
    } 
  }

  public VectorRemoteProgram program {
    set {
      nrc_interfacePINVOKE.RemoteControl_program_set(swigCPtr, VectorRemoteProgram.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.RemoteControl_program_get(swigCPtr);
      VectorRemoteProgram ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorRemoteProgram(cPtr, false);
      return ret;
    } 
  }

  public RemoteControl() : this(nrc_interfacePINVOKE.new_RemoteControl(), true) {
  }

}
