//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RobotJointParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RobotJointParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RobotJointParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RobotJointParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RobotJointParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_RobotJointParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double reducRatio {
    set {
      nrc_interfacePINVOKE.RobotJointParam_reducRatio_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_reducRatio_get(swigCPtr);
      return ret;
    } 
  }

  public int encoderResolution {
    set {
      nrc_interfacePINVOKE.RobotJointParam_encoderResolution_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RobotJointParam_encoderResolution_get(swigCPtr);
      return ret;
    } 
  }

  public double posSWLimit {
    set {
      nrc_interfacePINVOKE.RobotJointParam_posSWLimit_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_posSWLimit_get(swigCPtr);
      return ret;
    } 
  }

  public double negSWLimit {
    set {
      nrc_interfacePINVOKE.RobotJointParam_negSWLimit_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_negSWLimit_get(swigCPtr);
      return ret;
    } 
  }

  public double ratedRotSpeed {
    set {
      nrc_interfacePINVOKE.RobotJointParam_ratedRotSpeed_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_ratedRotSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public double ratedDeRotSpeed {
    set {
      nrc_interfacePINVOKE.RobotJointParam_ratedDeRotSpeed_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_ratedDeRotSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public double maxRotSpeed {
    set {
      nrc_interfacePINVOKE.RobotJointParam_maxRotSpeed_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_maxRotSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public double maxDeRotSpeed {
    set {
      nrc_interfacePINVOKE.RobotJointParam_maxDeRotSpeed_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_maxDeRotSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public double ratedVel {
    set {
      nrc_interfacePINVOKE.RobotJointParam_ratedVel_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_ratedVel_get(swigCPtr);
      return ret;
    } 
  }

  public double deRatedVel {
    set {
      nrc_interfacePINVOKE.RobotJointParam_deRatedVel_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_deRatedVel_get(swigCPtr);
      return ret;
    } 
  }

  public double maxAcc {
    set {
      nrc_interfacePINVOKE.RobotJointParam_maxAcc_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_maxAcc_get(swigCPtr);
      return ret;
    } 
  }

  public double maxDecel {
    set {
      nrc_interfacePINVOKE.RobotJointParam_maxDecel_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotJointParam_maxDecel_get(swigCPtr);
      return ret;
    } 
  }

  public int direction {
    set {
      nrc_interfacePINVOKE.RobotJointParam_direction_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RobotJointParam_direction_get(swigCPtr);
      return ret;
    } 
  }

  public RobotJointParam() : this(nrc_interfacePINVOKE.new_RobotJointParam(), true) {
  }

}
