//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RobotState : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RobotState(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RobotState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RobotState obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RobotState() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_RobotState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int channel {
    set {
      nrc_interfacePINVOKE.RobotState_channel_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RobotState_channel_get(swigCPtr);
      return ret;
    } 
  }

  public bool stop {
    set {
      nrc_interfacePINVOKE.RobotState_stop_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.RobotState_stop_get(swigCPtr);
      return ret;
    } 
  }

  public int mode {
    set {
      nrc_interfacePINVOKE.RobotState_mode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RobotState_mode_get(swigCPtr);
      return ret;
    } 
  }

  public int interval {
    set {
      nrc_interfacePINVOKE.RobotState_interval_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RobotState_interval_get(swigCPtr);
      return ret;
    } 
  }

  public bool ioState {
    set {
      nrc_interfacePINVOKE.RobotState_ioState_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.RobotState_ioState_get(swigCPtr);
      return ret;
    } 
  }

  public int position {
    set {
      nrc_interfacePINVOKE.RobotState_position_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RobotState_position_get(swigCPtr);
      return ret;
    } 
  }

  public bool dataildmotionpos {
    set {
      nrc_interfacePINVOKE.RobotState_dataildmotionpos_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.RobotState_dataildmotionpos_get(swigCPtr);
      return ret;
    } 
  }

  public int posSum {
    set {
      nrc_interfacePINVOKE.RobotState_posSum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RobotState_posSum_get(swigCPtr);
      return ret;
    } 
  }

  public VectorString ioPort {
    set {
      nrc_interfacePINVOKE.RobotState_ioPort_set(swigCPtr, VectorString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.RobotState_ioPort_get(swigCPtr);
      VectorString ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorString(cPtr, false);
      return ret;
    } 
  }

  public VectorString optional {
    set {
      nrc_interfacePINVOKE.RobotState_optional_set(swigCPtr, VectorString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.RobotState_optional_get(swigCPtr);
      VectorString ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorString(cPtr, false);
      return ret;
    } 
  }

  public RobotState() : this(nrc_interfacePINVOKE.new_RobotState(), true) {
  }

}
