//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RobotDHParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RobotDHParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RobotDHParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RobotDHParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RobotDHParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_RobotDHParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double L1 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L1_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L1_get(swigCPtr);
      return ret;
    } 
  }

  public double L2 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L2_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L2_get(swigCPtr);
      return ret;
    } 
  }

  public double L3 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L3_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L3_get(swigCPtr);
      return ret;
    } 
  }

  public double L4 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L4_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L4_get(swigCPtr);
      return ret;
    } 
  }

  public double L5 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L5_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L5_get(swigCPtr);
      return ret;
    } 
  }

  public double L6 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L6_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L6_get(swigCPtr);
      return ret;
    } 
  }

  public double L7 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L7_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L7_get(swigCPtr);
      return ret;
    } 
  }

  public double L8 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L8_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L8_get(swigCPtr);
      return ret;
    } 
  }

  public double L9 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L9_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L9_get(swigCPtr);
      return ret;
    } 
  }

  public double L10 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L10_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L10_get(swigCPtr);
      return ret;
    } 
  }

  public double L11 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L11_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L11_get(swigCPtr);
      return ret;
    } 
  }

  public double L12 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L12_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L12_get(swigCPtr);
      return ret;
    } 
  }

  public double L13 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L13_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L13_get(swigCPtr);
      return ret;
    } 
  }

  public double L14 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L14_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L14_get(swigCPtr);
      return ret;
    } 
  }

  public double L15 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L15_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L15_get(swigCPtr);
      return ret;
    } 
  }

  public double L16 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L16_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L16_get(swigCPtr);
      return ret;
    } 
  }

  public double L17 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L17_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L17_get(swigCPtr);
      return ret;
    } 
  }

  public double L18 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L18_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L18_get(swigCPtr);
      return ret;
    } 
  }

  public double L19 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L19_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L19_get(swigCPtr);
      return ret;
    } 
  }

  public double L20 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L20_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L20_get(swigCPtr);
      return ret;
    } 
  }

  public string Couple_Coe_1_2 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_1_2_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_1_2_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Couple_Coe_2_3 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_2_3_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_2_3_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Couple_Coe_3_2 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_3_2_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_3_2_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Couple_Coe_3_4 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_3_4_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_3_4_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Couple_Coe_4_5 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_4_5_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_4_5_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Couple_Coe_4_6 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_4_6_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_4_6_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Couple_Coe_5_6 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_5_6_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.RobotDHParam_Couple_Coe_5_6_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double dynamicLimit_max {
    set {
      nrc_interfacePINVOKE.RobotDHParam_dynamicLimit_max_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_dynamicLimit_max_get(swigCPtr);
      return ret;
    } 
  }

  public double dynamicLimit_min {
    set {
      nrc_interfacePINVOKE.RobotDHParam_dynamicLimit_min_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_dynamicLimit_min_get(swigCPtr);
      return ret;
    } 
  }

  public double pitch {
    set {
      nrc_interfacePINVOKE.RobotDHParam_pitch_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_pitch_get(swigCPtr);
      return ret;
    } 
  }

  public double sliding_lead_value {
    set {
      nrc_interfacePINVOKE.RobotDHParam_sliding_lead_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_sliding_lead_value_get(swigCPtr);
      return ret;
    } 
  }

  public double uplift_lead_value {
    set {
      nrc_interfacePINVOKE.RobotDHParam_uplift_lead_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_uplift_lead_value_get(swigCPtr);
      return ret;
    } 
  }

  public double spray_distance {
    set {
      nrc_interfacePINVOKE.RobotDHParam_spray_distance_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_spray_distance_get(swigCPtr);
      return ret;
    } 
  }

  public double threeAxisDirection {
    set {
      nrc_interfacePINVOKE.RobotDHParam_threeAxisDirection_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_threeAxisDirection_get(swigCPtr);
      return ret;
    } 
  }

  public double fiveAxisDirection {
    set {
      nrc_interfacePINVOKE.RobotDHParam_fiveAxisDirection_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_fiveAxisDirection_get(swigCPtr);
      return ret;
    } 
  }

  public double twoAxisConversionRatio {
    set {
      nrc_interfacePINVOKE.RobotDHParam_twoAxisConversionRatio_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_twoAxisConversionRatio_get(swigCPtr);
      return ret;
    } 
  }

  public double threeAxisConversionRatio {
    set {
      nrc_interfacePINVOKE.RobotDHParam_threeAxisConversionRatio_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_threeAxisConversionRatio_get(swigCPtr);
      return ret;
    } 
  }

  public double amplificationRatio {
    set {
      nrc_interfacePINVOKE.RobotDHParam_amplificationRatio_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_amplificationRatio_get(swigCPtr);
      return ret;
    } 
  }

  public double conversionratio_x {
    set {
      nrc_interfacePINVOKE.RobotDHParam_conversionratio_x_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_conversionratio_x_get(swigCPtr);
      return ret;
    } 
  }

  public double conversionratio_y {
    set {
      nrc_interfacePINVOKE.RobotDHParam_conversionratio_y_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_conversionratio_y_get(swigCPtr);
      return ret;
    } 
  }

  public double conversionratio_z {
    set {
      nrc_interfacePINVOKE.RobotDHParam_conversionratio_z_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_conversionratio_z_get(swigCPtr);
      return ret;
    } 
  }

  public double conversionratio_J1 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_conversionratio_J1_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_conversionratio_J1_get(swigCPtr);
      return ret;
    } 
  }

  public double conversionratio_J2 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_conversionratio_J2_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_conversionratio_J2_get(swigCPtr);
      return ret;
    } 
  }

  public double conversionratio_J3 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_conversionratio_J3_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_conversionratio_J3_get(swigCPtr);
      return ret;
    } 
  }

  public int upsideDown {
    set {
      nrc_interfacePINVOKE.RobotDHParam_upsideDown_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.RobotDHParam_upsideDown_get(swigCPtr);
      return ret;
    } 
  }

  public RobotDHParam() : this(nrc_interfacePINVOKE.new_RobotDHParam(), true) {
  }

}
