//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SafeIO : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SafeIO(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SafeIO obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SafeIO obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SafeIO() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_SafeIO(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int quickStopPort1 {
    set {
      nrc_interfacePINVOKE.SafeIO_quickStopPort1_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.SafeIO_quickStopPort1_get(swigCPtr);
      return ret;
    } 
  }

  public int quickStopPort2 {
    set {
      nrc_interfacePINVOKE.SafeIO_quickStopPort2_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.SafeIO_quickStopPort2_get(swigCPtr);
      return ret;
    } 
  }

  public int quickStopValue1 {
    set {
      nrc_interfacePINVOKE.SafeIO_quickStopValue1_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.SafeIO_quickStopValue1_get(swigCPtr);
      return ret;
    } 
  }

  public int quickStopValue2 {
    set {
      nrc_interfacePINVOKE.SafeIO_quickStopValue2_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.SafeIO_quickStopValue2_get(swigCPtr);
      return ret;
    } 
  }

  public bool quickStopEnable {
    set {
      nrc_interfacePINVOKE.SafeIO_quickStopEnable_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.SafeIO_quickStopEnable_get(swigCPtr);
      return ret;
    } 
  }

  public bool quickStopShied1 {
    set {
      nrc_interfacePINVOKE.SafeIO_quickStopShied1_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.SafeIO_quickStopShied1_get(swigCPtr);
      return ret;
    } 
  }

  public bool quickStopShied2 {
    set {
      nrc_interfacePINVOKE.SafeIO_quickStopShied2_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.SafeIO_quickStopShied2_get(swigCPtr);
      return ret;
    } 
  }

  public double quickStopTime {
    set {
      nrc_interfacePINVOKE.SafeIO_quickStopTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.SafeIO_quickStopTime_get(swigCPtr);
      return ret;
    } 
  }

  public int quickStopShiedTime {
    set {
      nrc_interfacePINVOKE.SafeIO_quickStopShiedTime_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.SafeIO_quickStopShiedTime_get(swigCPtr);
      return ret;
    } 
  }

  public int screenPort1 {
    set {
      nrc_interfacePINVOKE.SafeIO_screenPort1_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.SafeIO_screenPort1_get(swigCPtr);
      return ret;
    } 
  }

  public int screenPort2 {
    set {
      nrc_interfacePINVOKE.SafeIO_screenPort2_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.SafeIO_screenPort2_get(swigCPtr);
      return ret;
    } 
  }

  public int screenValue1 {
    set {
      nrc_interfacePINVOKE.SafeIO_screenValue1_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.SafeIO_screenValue1_get(swigCPtr);
      return ret;
    } 
  }

  public int screenValue2 {
    set {
      nrc_interfacePINVOKE.SafeIO_screenValue2_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.SafeIO_screenValue2_get(swigCPtr);
      return ret;
    } 
  }

  public bool screenEnable {
    set {
      nrc_interfacePINVOKE.SafeIO_screenEnable_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.SafeIO_screenEnable_get(swigCPtr);
      return ret;
    } 
  }

  public SafeIO() : this(nrc_interfacePINVOKE.new_SafeIO(), true) {
  }

}
