//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ServoMovePara : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ServoMovePara(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ServoMovePara obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ServoMovePara obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ServoMovePara() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ServoMovePara(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool clearBuffer {
    set {
      nrc_interfacePINVOKE.ServoMovePara_clearBuffer_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.ServoMovePara_clearBuffer_get(swigCPtr);
      return ret;
    } 
  }

  public int targetMode {
    set {
      nrc_interfacePINVOKE.ServoMovePara_targetMode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoMovePara_targetMode_get(swigCPtr);
      return ret;
    } 
  }

  public int sendMode {
    set {
      nrc_interfacePINVOKE.ServoMovePara_sendMode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoMovePara_sendMode_get(swigCPtr);
      return ret;
    } 
  }

  public int runMode {
    set {
      nrc_interfacePINVOKE.ServoMovePara_runMode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoMovePara_runMode_get(swigCPtr);
      return ret;
    } 
  }

  public int sum {
    set {
      nrc_interfacePINVOKE.ServoMovePara_sum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoMovePara_sum_get(swigCPtr);
      return ret;
    } 
  }

  public int count {
    set {
      nrc_interfacePINVOKE.ServoMovePara_count_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoMovePara_count_get(swigCPtr);
      return ret;
    } 
  }

  public int coord {
    set {
      nrc_interfacePINVOKE.ServoMovePara_coord_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoMovePara_coord_get(swigCPtr);
      return ret;
    } 
  }

  public int extMove {
    set {
      nrc_interfacePINVOKE.ServoMovePara_extMove_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoMovePara_extMove_get(swigCPtr);
      return ret;
    } 
  }

  public int size {
    set {
      nrc_interfacePINVOKE.ServoMovePara_size_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoMovePara_size_get(swigCPtr);
      return ret;
    } 
  }

  public VectorVectorDouble pos {
    set {
      nrc_interfacePINVOKE.ServoMovePara_pos_set(swigCPtr, VectorVectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.ServoMovePara_pos_get(swigCPtr);
      VectorVectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorDouble(cPtr, false);
      return ret;
    } 
  }

  public VectorVectorDouble axisvel {
    set {
      nrc_interfacePINVOKE.ServoMovePara_axisvel_set(swigCPtr, VectorVectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.ServoMovePara_axisvel_get(swigCPtr);
      VectorVectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorDouble(cPtr, false);
      return ret;
    } 
  }

  public VectorVectorDouble axisacc {
    set {
      nrc_interfacePINVOKE.ServoMovePara_axisacc_set(swigCPtr, VectorVectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.ServoMovePara_axisacc_get(swigCPtr);
      VectorVectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorDouble(cPtr, false);
      return ret;
    } 
  }

  public VectorDouble timeStamp {
    set {
      nrc_interfacePINVOKE.ServoMovePara_timeStamp_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.ServoMovePara_timeStamp_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public ServoMovePara() : this(nrc_interfacePINVOKE.new_ServoMovePara(), true) {
  }

}
