//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ServoPointMovePara : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ServoPointMovePara(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ServoPointMovePara obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ServoPointMovePara obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ServoPointMovePara() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ServoPointMovePara(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool end {
    set {
      nrc_interfacePINVOKE.ServoPointMovePara_end_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.ServoPointMovePara_end_get(swigCPtr);
      return ret;
    } 
  }

  public int sum {
    set {
      nrc_interfacePINVOKE.ServoPointMovePara_sum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoPointMovePara_sum_get(swigCPtr);
      return ret;
    } 
  }

  public int count {
    set {
      nrc_interfacePINVOKE.ServoPointMovePara_count_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ServoPointMovePara_count_get(swigCPtr);
      return ret;
    } 
  }

  public VectorVectorDouble pos {
    set {
      nrc_interfacePINVOKE.ServoPointMovePara_pos_set(swigCPtr, VectorVectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.ServoPointMovePara_pos_get(swigCPtr);
      VectorVectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorDouble(cPtr, false);
      return ret;
    } 
  }

  public ServoPointMovePara() : this(nrc_interfacePINVOKE.new_ServoPointMovePara(), true) {
  }

}
