//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Socket : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Socket(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Socket obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Socket obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Socket() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_Socket(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string IP {
    set {
      nrc_interfacePINVOKE.Socket_IP_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Socket_IP_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int cameraDataType {
    set {
      nrc_interfacePINVOKE.Socket_cameraDataType_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Socket_cameraDataType_get(swigCPtr);
      return ret;
    } 
  }

  public int portNum {
    set {
      nrc_interfacePINVOKE.Socket_portNum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Socket_portNum_get(swigCPtr);
      return ret;
    } 
  }

  public int portOne {
    set {
      nrc_interfacePINVOKE.Socket_portOne_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Socket_portOne_get(swigCPtr);
      return ret;
    } 
  }

  public int portTwo {
    set {
      nrc_interfacePINVOKE.Socket_portTwo_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Socket_portTwo_get(swigCPtr);
      return ret;
    } 
  }

  public bool server {
    set {
      nrc_interfacePINVOKE.Socket_server_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.Socket_server_get(swigCPtr);
      return ret;
    } 
  }

  public Socket() : this(nrc_interfacePINVOKE.new_Socket(), true) {
  }

}
