//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorVectorCondition : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<VectorCondition>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorVectorCondition(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorVectorCondition obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorVectorCondition obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorVectorCondition() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VectorVectorCondition(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorVectorCondition(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VectorCondition element in c) {
      this.Add(element);
    }
  }

  public VectorVectorCondition(global::System.Collections.Generic.IEnumerable<VectorCondition> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VectorCondition element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public VectorCondition this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(VectorCondition[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(VectorCondition[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, VectorCondition[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public VectorCondition[] ToArray() {
    VectorCondition[] array = new VectorCondition[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<VectorCondition> global::System.Collections.Generic.IEnumerable<VectorCondition>.GetEnumerator() {
    return new VectorVectorConditionEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorVectorConditionEnumerator(this);
  }

  public VectorVectorConditionEnumerator GetEnumerator() {
    return new VectorVectorConditionEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorVectorConditionEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<VectorCondition>
  {
    private VectorVectorCondition collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorVectorConditionEnumerator(VectorVectorCondition collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public VectorCondition Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (VectorCondition)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorVectorCondition() : this(nrc_interfacePINVOKE.new_VectorVectorCondition__SWIG_0(), true) {
  }

  public VectorVectorCondition(VectorVectorCondition other) : this(nrc_interfacePINVOKE.new_VectorVectorCondition__SWIG_1(VectorVectorCondition.getCPtr(other)), true) {
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    nrc_interfacePINVOKE.VectorVectorCondition_Clear(swigCPtr);
  }

  public void Add(VectorCondition x) {
    nrc_interfacePINVOKE.VectorVectorCondition_Add(swigCPtr, VectorCondition.getCPtr(x));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = nrc_interfacePINVOKE.VectorVectorCondition_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = nrc_interfacePINVOKE.VectorVectorCondition_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = nrc_interfacePINVOKE.VectorVectorCondition_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    nrc_interfacePINVOKE.VectorVectorCondition_reserve(swigCPtr, n);
  }

  public VectorVectorCondition(int capacity) : this(nrc_interfacePINVOKE.new_VectorVectorCondition__SWIG_2(capacity), true) {
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  private VectorCondition getitemcopy(int index) {
    VectorCondition ret = new VectorCondition(nrc_interfacePINVOKE.VectorVectorCondition_getitemcopy(swigCPtr, index), true);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private VectorCondition getitem(int index) {
    VectorCondition ret = new VectorCondition(nrc_interfacePINVOKE.VectorVectorCondition_getitem(swigCPtr, index), false);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, VectorCondition val) {
    nrc_interfacePINVOKE.VectorVectorCondition_setitem(swigCPtr, index, VectorCondition.getCPtr(val));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorVectorCondition values) {
    nrc_interfacePINVOKE.VectorVectorCondition_AddRange(swigCPtr, VectorVectorCondition.getCPtr(values));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorVectorCondition GetRange(int index, int count) {
    global::System.IntPtr cPtr = nrc_interfacePINVOKE.VectorVectorCondition_GetRange(swigCPtr, index, count);
    VectorVectorCondition ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorCondition(cPtr, true);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, VectorCondition x) {
    nrc_interfacePINVOKE.VectorVectorCondition_Insert(swigCPtr, index, VectorCondition.getCPtr(x));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorVectorCondition values) {
    nrc_interfacePINVOKE.VectorVectorCondition_InsertRange(swigCPtr, index, VectorVectorCondition.getCPtr(values));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    nrc_interfacePINVOKE.VectorVectorCondition_RemoveAt(swigCPtr, index);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    nrc_interfacePINVOKE.VectorVectorCondition_RemoveRange(swigCPtr, index, count);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorVectorCondition Repeat(VectorCondition value, int count) {
    global::System.IntPtr cPtr = nrc_interfacePINVOKE.VectorVectorCondition_Repeat(VectorCondition.getCPtr(value), count);
    VectorVectorCondition ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorCondition(cPtr, true);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    nrc_interfacePINVOKE.VectorVectorCondition_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    nrc_interfacePINVOKE.VectorVectorCondition_Reverse__SWIG_1(swigCPtr, index, count);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorVectorCondition values) {
    nrc_interfacePINVOKE.VectorVectorCondition_SetRange(swigCPtr, index, VectorVectorCondition.getCPtr(values));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

}
