//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorAlarmdIO : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<AlarmdIO>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorAlarmdIO(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorAlarmdIO obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorAlarmdIO obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorAlarmdIO() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VectorAlarmdIO(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorAlarmdIO(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (AlarmdIO element in c) {
      this.Add(element);
    }
  }

  public VectorAlarmdIO(global::System.Collections.Generic.IEnumerable<AlarmdIO> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (AlarmdIO element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public AlarmdIO this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(AlarmdIO[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(AlarmdIO[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, AlarmdIO[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public AlarmdIO[] ToArray() {
    AlarmdIO[] array = new AlarmdIO[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<AlarmdIO> global::System.Collections.Generic.IEnumerable<AlarmdIO>.GetEnumerator() {
    return new VectorAlarmdIOEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorAlarmdIOEnumerator(this);
  }

  public VectorAlarmdIOEnumerator GetEnumerator() {
    return new VectorAlarmdIOEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorAlarmdIOEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<AlarmdIO>
  {
    private VectorAlarmdIO collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorAlarmdIOEnumerator(VectorAlarmdIO collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public AlarmdIO Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (AlarmdIO)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorAlarmdIO() : this(nrc_interfacePINVOKE.new_VectorAlarmdIO__SWIG_0(), true) {
  }

  public VectorAlarmdIO(VectorAlarmdIO other) : this(nrc_interfacePINVOKE.new_VectorAlarmdIO__SWIG_1(VectorAlarmdIO.getCPtr(other)), true) {
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    nrc_interfacePINVOKE.VectorAlarmdIO_Clear(swigCPtr);
  }

  public void Add(AlarmdIO x) {
    nrc_interfacePINVOKE.VectorAlarmdIO_Add(swigCPtr, AlarmdIO.getCPtr(x));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = nrc_interfacePINVOKE.VectorAlarmdIO_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = nrc_interfacePINVOKE.VectorAlarmdIO_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = nrc_interfacePINVOKE.VectorAlarmdIO_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    nrc_interfacePINVOKE.VectorAlarmdIO_reserve(swigCPtr, n);
  }

  public VectorAlarmdIO(int capacity) : this(nrc_interfacePINVOKE.new_VectorAlarmdIO__SWIG_2(capacity), true) {
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  private AlarmdIO getitemcopy(int index) {
    AlarmdIO ret = new AlarmdIO(nrc_interfacePINVOKE.VectorAlarmdIO_getitemcopy(swigCPtr, index), true);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private AlarmdIO getitem(int index) {
    AlarmdIO ret = new AlarmdIO(nrc_interfacePINVOKE.VectorAlarmdIO_getitem(swigCPtr, index), false);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, AlarmdIO val) {
    nrc_interfacePINVOKE.VectorAlarmdIO_setitem(swigCPtr, index, AlarmdIO.getCPtr(val));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorAlarmdIO values) {
    nrc_interfacePINVOKE.VectorAlarmdIO_AddRange(swigCPtr, VectorAlarmdIO.getCPtr(values));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorAlarmdIO GetRange(int index, int count) {
    global::System.IntPtr cPtr = nrc_interfacePINVOKE.VectorAlarmdIO_GetRange(swigCPtr, index, count);
    VectorAlarmdIO ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorAlarmdIO(cPtr, true);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, AlarmdIO x) {
    nrc_interfacePINVOKE.VectorAlarmdIO_Insert(swigCPtr, index, AlarmdIO.getCPtr(x));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorAlarmdIO values) {
    nrc_interfacePINVOKE.VectorAlarmdIO_InsertRange(swigCPtr, index, VectorAlarmdIO.getCPtr(values));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    nrc_interfacePINVOKE.VectorAlarmdIO_RemoveAt(swigCPtr, index);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    nrc_interfacePINVOKE.VectorAlarmdIO_RemoveRange(swigCPtr, index, count);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorAlarmdIO Repeat(AlarmdIO value, int count) {
    global::System.IntPtr cPtr = nrc_interfacePINVOKE.VectorAlarmdIO_Repeat(AlarmdIO.getCPtr(value), count);
    VectorAlarmdIO ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorAlarmdIO(cPtr, true);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    nrc_interfacePINVOKE.VectorAlarmdIO_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    nrc_interfacePINVOKE.VectorAlarmdIO_Reverse__SWIG_1(swigCPtr, index, count);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorAlarmdIO values) {
    nrc_interfacePINVOKE.VectorAlarmdIO_SetRange(swigCPtr, index, VectorAlarmdIO.getCPtr(values));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

}
