//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorRemoteProgram : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<RemoteProgram>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorRemoteProgram(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorRemoteProgram obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorRemoteProgram obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorRemoteProgram() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VectorRemoteProgram(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorRemoteProgram(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (RemoteProgram element in c) {
      this.Add(element);
    }
  }

  public VectorRemoteProgram(global::System.Collections.Generic.IEnumerable<RemoteProgram> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (RemoteProgram element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public RemoteProgram this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(RemoteProgram[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(RemoteProgram[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, RemoteProgram[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public RemoteProgram[] ToArray() {
    RemoteProgram[] array = new RemoteProgram[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<RemoteProgram> global::System.Collections.Generic.IEnumerable<RemoteProgram>.GetEnumerator() {
    return new VectorRemoteProgramEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorRemoteProgramEnumerator(this);
  }

  public VectorRemoteProgramEnumerator GetEnumerator() {
    return new VectorRemoteProgramEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorRemoteProgramEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<RemoteProgram>
  {
    private VectorRemoteProgram collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorRemoteProgramEnumerator(VectorRemoteProgram collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public RemoteProgram Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (RemoteProgram)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorRemoteProgram() : this(nrc_interfacePINVOKE.new_VectorRemoteProgram__SWIG_0(), true) {
  }

  public VectorRemoteProgram(VectorRemoteProgram other) : this(nrc_interfacePINVOKE.new_VectorRemoteProgram__SWIG_1(VectorRemoteProgram.getCPtr(other)), true) {
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    nrc_interfacePINVOKE.VectorRemoteProgram_Clear(swigCPtr);
  }

  public void Add(RemoteProgram x) {
    nrc_interfacePINVOKE.VectorRemoteProgram_Add(swigCPtr, RemoteProgram.getCPtr(x));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = nrc_interfacePINVOKE.VectorRemoteProgram_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = nrc_interfacePINVOKE.VectorRemoteProgram_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = nrc_interfacePINVOKE.VectorRemoteProgram_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    nrc_interfacePINVOKE.VectorRemoteProgram_reserve(swigCPtr, n);
  }

  public VectorRemoteProgram(int capacity) : this(nrc_interfacePINVOKE.new_VectorRemoteProgram__SWIG_2(capacity), true) {
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  private RemoteProgram getitemcopy(int index) {
    RemoteProgram ret = new RemoteProgram(nrc_interfacePINVOKE.VectorRemoteProgram_getitemcopy(swigCPtr, index), true);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private RemoteProgram getitem(int index) {
    RemoteProgram ret = new RemoteProgram(nrc_interfacePINVOKE.VectorRemoteProgram_getitem(swigCPtr, index), false);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, RemoteProgram val) {
    nrc_interfacePINVOKE.VectorRemoteProgram_setitem(swigCPtr, index, RemoteProgram.getCPtr(val));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorRemoteProgram values) {
    nrc_interfacePINVOKE.VectorRemoteProgram_AddRange(swigCPtr, VectorRemoteProgram.getCPtr(values));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorRemoteProgram GetRange(int index, int count) {
    global::System.IntPtr cPtr = nrc_interfacePINVOKE.VectorRemoteProgram_GetRange(swigCPtr, index, count);
    VectorRemoteProgram ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorRemoteProgram(cPtr, true);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, RemoteProgram x) {
    nrc_interfacePINVOKE.VectorRemoteProgram_Insert(swigCPtr, index, RemoteProgram.getCPtr(x));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorRemoteProgram values) {
    nrc_interfacePINVOKE.VectorRemoteProgram_InsertRange(swigCPtr, index, VectorRemoteProgram.getCPtr(values));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    nrc_interfacePINVOKE.VectorRemoteProgram_RemoveAt(swigCPtr, index);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    nrc_interfacePINVOKE.VectorRemoteProgram_RemoveRange(swigCPtr, index, count);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorRemoteProgram Repeat(RemoteProgram value, int count) {
    global::System.IntPtr cPtr = nrc_interfacePINVOKE.VectorRemoteProgram_Repeat(RemoteProgram.getCPtr(value), count);
    VectorRemoteProgram ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorRemoteProgram(cPtr, true);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    nrc_interfacePINVOKE.VectorRemoteProgram_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    nrc_interfacePINVOKE.VectorRemoteProgram_Reverse__SWIG_1(swigCPtr, index, count);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorRemoteProgram values) {
    nrc_interfacePINVOKE.VectorRemoteProgram_SetRange(swigCPtr, index, VectorRemoteProgram.getCPtr(values));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
  }

}
