//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VFDRunParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VFDRunParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VFDRunParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VFDRunParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VFDRunParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VFDRunParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int dir {
    set {
      nrc_interfacePINVOKE.VFDRunParam_dir_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.VFDRunParam_dir_get(swigCPtr);
      return ret;
    } 
  }

  public int vel {
    set {
      nrc_interfacePINVOKE.VFDRunParam_vel_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.VFDRunParam_vel_get(swigCPtr);
      return ret;
    } 
  }

  public int acceleration {
    set {
      nrc_interfacePINVOKE.VFDRunParam_acceleration_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.VFDRunParam_acceleration_get(swigCPtr);
      return ret;
    } 
  }

  public int deceleration {
    set {
      nrc_interfacePINVOKE.VFDRunParam_deceleration_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.VFDRunParam_deceleration_get(swigCPtr);
      return ret;
    } 
  }

  public bool independent_axis {
    set {
      nrc_interfacePINVOKE.VFDRunParam_independent_axis_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.VFDRunParam_independent_axis_get(swigCPtr);
      return ret;
    } 
  }

  public VFDRunParam() : this(nrc_interfacePINVOKE.new_VFDRunParam(), true) {
  }

}
