//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VisionCalibrationData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VisionCalibrationData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VisionCalibrationData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VisionCalibrationData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VisionCalibrationData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VisionCalibrationData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int visionNum {
    set {
      nrc_interfacePINVOKE.VisionCalibrationData_visionNum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.VisionCalibrationData_visionNum_get(swigCPtr);
      return ret;
    } 
  }

  public Calibration calibration {
    set {
      nrc_interfacePINVOKE.VisionCalibrationData_calibration_set(swigCPtr, Calibration.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionCalibrationData_calibration_get(swigCPtr);
      Calibration ret = (cPtr == global::System.IntPtr.Zero) ? null : new Calibration(cPtr, false);
      return ret;
    } 
  }

  public VisionCalibrationData(int num_points) : this(nrc_interfacePINVOKE.new_VisionCalibrationData__SWIG_0(num_points), true) {
  }

  public VisionCalibrationData() : this(nrc_interfacePINVOKE.new_VisionCalibrationData__SWIG_1(), true) {
  }

}
