//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class WaveParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WaveParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WaveParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(WaveParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WaveParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_WaveParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int type {
    set {
      nrc_interfacePINVOKE.WaveParam_type_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.WaveParam_type_get(swigCPtr);
      return ret;
    } 
  }

  public double swingFreq {
    set {
      nrc_interfacePINVOKE.WaveParam_swingFreq_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WaveParam_swingFreq_get(swigCPtr);
      return ret;
    } 
  }

  public double swingAmplitude {
    set {
      nrc_interfacePINVOKE.WaveParam_swingAmplitude_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WaveParam_swingAmplitude_get(swigCPtr);
      return ret;
    } 
  }

  public double radius {
    set {
      nrc_interfacePINVOKE.WaveParam_radius_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WaveParam_radius_get(swigCPtr);
      return ret;
    } 
  }

  public double LTypeAngle {
    set {
      nrc_interfacePINVOKE.WaveParam_LTypeAngle_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WaveParam_LTypeAngle_get(swigCPtr);
      return ret;
    } 
  }

  public bool moveWhenEdgeStay {
    set {
      nrc_interfacePINVOKE.WaveParam_moveWhenEdgeStay_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.WaveParam_moveWhenEdgeStay_get(swigCPtr);
      return ret;
    } 
  }

  public double leftStayTime {
    set {
      nrc_interfacePINVOKE.WaveParam_leftStayTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WaveParam_leftStayTime_get(swigCPtr);
      return ret;
    } 
  }

  public double rightStayTime {
    set {
      nrc_interfacePINVOKE.WaveParam_rightStayTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WaveParam_rightStayTime_get(swigCPtr);
      return ret;
    } 
  }

  public int initialDir {
    set {
      nrc_interfacePINVOKE.WaveParam_initialDir_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.WaveParam_initialDir_get(swigCPtr);
      return ret;
    } 
  }

  public double horizontalDeflection {
    set {
      nrc_interfacePINVOKE.WaveParam_horizontalDeflection_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WaveParam_horizontalDeflection_get(swigCPtr);
      return ret;
    } 
  }

  public double verticalDeflection {
    set {
      nrc_interfacePINVOKE.WaveParam_verticalDeflection_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WaveParam_verticalDeflection_get(swigCPtr);
      return ret;
    } 
  }

  public WaveParam() : this(nrc_interfacePINVOKE.new_WaveParam(), true) {
  }

}
