//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class WeldState : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WeldState(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WeldState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(WeldState obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WeldState() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_WeldState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int pistolSwitch {
    set {
      nrc_interfacePINVOKE.WeldState_pistolSwitch_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.WeldState_pistolSwitch_get(swigCPtr);
      return ret;
    } 
  }

  public int arcingSuccess {
    set {
      nrc_interfacePINVOKE.WeldState_arcingSuccess_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.WeldState_arcingSuccess_get(swigCPtr);
      return ret;
    } 
  }

  public int handWireFeed {
    set {
      nrc_interfacePINVOKE.WeldState_handWireFeed_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.WeldState_handWireFeed_get(swigCPtr);
      return ret;
    } 
  }

  public double weldCurrent {
    set {
      nrc_interfacePINVOKE.WeldState_weldCurrent_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WeldState_weldCurrent_get(swigCPtr);
      return ret;
    } 
  }

  public double weldVoltage {
    set {
      nrc_interfacePINVOKE.WeldState_weldVoltage_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WeldState_weldVoltage_get(swigCPtr);
      return ret;
    } 
  }

  public double weldTime {
    set {
      nrc_interfacePINVOKE.WeldState_weldTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WeldState_weldTime_get(swigCPtr);
      return ret;
    } 
  }

  public double weldPWM {
    set {
      nrc_interfacePINVOKE.WeldState_weldPWM_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.WeldState_weldPWM_get(swigCPtr);
      return ret;
    } 
  }

  public WeldState() : this(nrc_interfacePINVOKE.new_WeldState(), true) {
  }

}
