//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class AlarmdIO : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AlarmdIO(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AlarmdIO obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AlarmdIO obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AlarmdIO() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_AlarmdIO(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int msgType {
    set {
      nrc_interfacePINVOKE.AlarmdIO_msgType_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.AlarmdIO_msgType_get(swigCPtr);
      return ret;
    } 
  }

  public int value {
    set {
      nrc_interfacePINVOKE.AlarmdIO_value_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.AlarmdIO_value_get(swigCPtr);
      return ret;
    } 
  }

  public int enable {
    set {
      nrc_interfacePINVOKE.AlarmdIO_enable_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.AlarmdIO_enable_get(swigCPtr);
      return ret;
    } 
  }

  public string msg {
    set {
      nrc_interfacePINVOKE.AlarmdIO_msg_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.AlarmdIO_msg_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public AlarmdIO() : this(nrc_interfacePINVOKE.new_AlarmdIO(), true) {
  }

}
