//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ArcParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ArcParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ArcParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ArcParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ArcParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ArcParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double weldVoltage {
    set {
      nrc_interfacePINVOKE.ArcParam_weldVoltage_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_weldVoltage_get(swigCPtr);
      return ret;
    } 
  }

  public double weldCurrent {
    set {
      nrc_interfacePINVOKE.ArcParam_weldCurrent_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_weldCurrent_get(swigCPtr);
      return ret;
    } 
  }

  public double arcOnCurrent {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOnCurrent_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_arcOnCurrent_get(swigCPtr);
      return ret;
    } 
  }

  public double arcOnVoltage {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOnVoltage_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_arcOnVoltage_get(swigCPtr);
      return ret;
    } 
  }

  public double arcOnTime {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOnTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_arcOnTime_get(swigCPtr);
      return ret;
    } 
  }

  public bool arcOnRampEnable {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOnRampEnable_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.ArcParam_arcOnRampEnable_get(swigCPtr);
      return ret;
    } 
  }

  public int arcOnRampMode {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOnRampMode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ArcParam_arcOnRampMode_get(swigCPtr);
      return ret;
    } 
  }

  public double arcOnRampTime {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOnRampTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_arcOnRampTime_get(swigCPtr);
      return ret;
    } 
  }

  public double arcOffCurrent {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOffCurrent_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_arcOffCurrent_get(swigCPtr);
      return ret;
    } 
  }

  public double arcOffVoltage {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOffVoltage_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_arcOffVoltage_get(swigCPtr);
      return ret;
    } 
  }

  public double arcOffTime {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOffTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_arcOffTime_get(swigCPtr);
      return ret;
    } 
  }

  public bool arcOffRampEnable {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOffRampEnable_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.ArcParam_arcOffRampEnable_get(swigCPtr);
      return ret;
    } 
  }

  public int arcOffRampMode {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOffRampMode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ArcParam_arcOffRampMode_get(swigCPtr);
      return ret;
    } 
  }

  public double arcOffRampTime {
    set {
      nrc_interfacePINVOKE.ArcParam_arcOffRampTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ArcParam_arcOffRampTime_get(swigCPtr);
      return ret;
    } 
  }

  public ArcParam() : this(nrc_interfacePINVOKE.new_ArcParam(), true) {
  }

}
