//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class AxisTorque : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AxisTorque(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AxisTorque obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AxisTorque obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AxisTorque() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_AxisTorque(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int axis_set_num {
    set {
      nrc_interfacePINVOKE.AxisTorque_axis_set_num_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.AxisTorque_axis_set_num_get(swigCPtr);
      return ret;
    } 
  }

  public double axis_set_torque {
    set {
      nrc_interfacePINVOKE.AxisTorque_axis_set_torque_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.AxisTorque_axis_set_torque_get(swigCPtr);
      return ret;
    } 
  }

  public double axis_torque_slope {
    set {
      nrc_interfacePINVOKE.AxisTorque_axis_torque_slope_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.AxisTorque_axis_torque_slope_get(swigCPtr);
      return ret;
    } 
  }

  public AxisTorque() : this(nrc_interfacePINVOKE.new_AxisTorque(), true) {
  }

}
