//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class AXISPostion : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AXISPostion(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AXISPostion obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AXISPostion obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AXISPostion() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_AXISPostion(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int axis_set_num {
    set {
      nrc_interfacePINVOKE.AXISPostion_axis_set_num_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.AXISPostion_axis_set_num_get(swigCPtr);
      return ret;
    } 
  }

  public int axis_set_type {
    set {
      nrc_interfacePINVOKE.AXISPostion_axis_set_type_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.AXISPostion_axis_set_type_get(swigCPtr);
      return ret;
    } 
  }

  public RunType control_axis_run_type {
    set {
      nrc_interfacePINVOKE.AXISPostion_control_axis_run_type_set(swigCPtr, (int)value);
    } 
    get {
      RunType ret = (RunType)nrc_interfacePINVOKE.AXISPostion_control_axis_run_type_get(swigCPtr);
      return ret;
    } 
  }

  public double axis_target_pos {
    set {
      nrc_interfacePINVOKE.AXISPostion_axis_target_pos_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.AXISPostion_axis_target_pos_get(swigCPtr);
      return ret;
    } 
  }

  public double axis_set_speed {
    set {
      nrc_interfacePINVOKE.AXISPostion_axis_set_speed_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.AXISPostion_axis_set_speed_get(swigCPtr);
      return ret;
    } 
  }

  public double axis_set_acc {
    set {
      nrc_interfacePINVOKE.AXISPostion_axis_set_acc_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.AXISPostion_axis_set_acc_get(swigCPtr);
      return ret;
    } 
  }

  public double axis_set_dec {
    set {
      nrc_interfacePINVOKE.AXISPostion_axis_set_dec_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.AXISPostion_axis_set_dec_get(swigCPtr);
      return ret;
    } 
  }

  public AXISPostion() : this(nrc_interfacePINVOKE.new_AXISPostion(), true) {
  }

}
