//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CalibrationPoint : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CalibrationPoint(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CalibrationPoint obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CalibrationPoint obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CalibrationPoint() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_CalibrationPoint(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorDouble pixel_pos {
    set {
      nrc_interfacePINVOKE.CalibrationPoint_pixel_pos_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.CalibrationPoint_pixel_pos_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public VectorDouble pixel_pos_deg {
    set {
      nrc_interfacePINVOKE.CalibrationPoint_pixel_pos_deg_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.CalibrationPoint_pixel_pos_deg_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public VectorDouble robot_pos {
    set {
      nrc_interfacePINVOKE.CalibrationPoint_robot_pos_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.CalibrationPoint_robot_pos_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public VectorDouble robot_pos_deg {
    set {
      nrc_interfacePINVOKE.CalibrationPoint_robot_pos_deg_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.CalibrationPoint_robot_pos_deg_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public CalibrationPoint() : this(nrc_interfacePINVOKE.new_CalibrationPoint(), true) {
  }

}
