//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ConveyorIdentificationParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConveyorIdentificationParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConveyorIdentificationParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConveyorIdentificationParams obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConveyorIdentificationParams() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ConveyorIdentificationParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int conveyorID {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_conveyorID_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_conveyorID_get(swigCPtr);
      return ret;
    } 
  }

  public int detectSrc_DI_capturePos {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_DI_capturePos_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_DI_capturePos_get(swigCPtr);
      return ret;
    } 
  }

  public string detectSrc_globalVar {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_globalVar_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_globalVar_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int detectSrc_type {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_type_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_type_get(swigCPtr);
      return ret;
    } 
  }

  public int detectSrc_visionID {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_visionID_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_visionID_get(swigCPtr);
      return ret;
    } 
  }

  public int detectSrc_vision_io_filter_type {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_vision_io_filter_type_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_vision_io_filter_type_get(swigCPtr);
      return ret;
    } 
  }

  public int detectSrc_vision_latch_encoder_value_type {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_vision_latch_encoder_value_type_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_detectSrc_vision_latch_encoder_value_type_get(swigCPtr);
      return ret;
    } 
  }

  public string identification_communication {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_identification_communication_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_identification_communication_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int identification_sensorTrg {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_identification_sensorTrg_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_identification_sensorTrg_get(swigCPtr);
      return ret;
    } 
  }

  public int identification_type {
    set {
      nrc_interfacePINVOKE.ConveyorIdentificationParams_identification_type_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorIdentificationParams_identification_type_get(swigCPtr);
      return ret;
    } 
  }

  public ConveyorIdentificationParams() : this(nrc_interfacePINVOKE.new_ConveyorIdentificationParams(), true) {
  }

}
