//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ConveyorWaitPointParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConveyorWaitPointParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConveyorWaitPointParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConveyorWaitPointParams obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConveyorWaitPointParams() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ConveyorWaitPointParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int conveyorID {
    set {
      nrc_interfacePINVOKE.ConveyorWaitPointParams_conveyorID_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorWaitPointParams_conveyorID_get(swigCPtr);
      return ret;
    } 
  }

  public double delayDetectTime {
    set {
      nrc_interfacePINVOKE.ConveyorWaitPointParams_delayDetectTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorWaitPointParams_delayDetectTime_get(swigCPtr);
      return ret;
    } 
  }

  public bool isWait {
    set {
      nrc_interfacePINVOKE.ConveyorWaitPointParams_isWait_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.ConveyorWaitPointParams_isWait_get(swigCPtr);
      return ret;
    } 
  }

  public VectorDouble pos {
    set {
      nrc_interfacePINVOKE.ConveyorWaitPointParams_pos_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.ConveyorWaitPointParams_pos_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public ConveyorWaitPointParams() : this(nrc_interfacePINVOKE.new_ConveyorWaitPointParams(), true) {
  }

}
