//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ConveyorTrackRangeParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConveyorTrackRangeParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConveyorTrackRangeParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConveyorTrackRangeParams obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConveyorTrackRangeParams() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ConveyorTrackRangeParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int conveyorID {
    set {
      nrc_interfacePINVOKE.ConveyorTrackRangeParams_conveyorID_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.ConveyorTrackRangeParams_conveyorID_get(swigCPtr);
      return ret;
    } 
  }

  public double position_receLatestPos {
    set {
      nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_receLatestPos_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_receLatestPos_get(swigCPtr);
      return ret;
    } 
  }

  public double position_trackRangeXMax {
    set {
      nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeXMax_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeXMax_get(swigCPtr);
      return ret;
    } 
  }

  public double position_trackRangeYMax {
    set {
      nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeYMax_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeYMax_get(swigCPtr);
      return ret;
    } 
  }

  public double position_trackRangeYMin {
    set {
      nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeYMin_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeYMin_get(swigCPtr);
      return ret;
    } 
  }

  public double position_trackRangeZMax {
    set {
      nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeZMax_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeZMax_get(swigCPtr);
      return ret;
    } 
  }

  public double position_trackRangeZMin {
    set {
      nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeZMin_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackRangeZMin_get(swigCPtr);
      return ret;
    } 
  }

  public double position_trackStartXPoint {
    set {
      nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackStartXPoint_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ConveyorTrackRangeParams_position_trackStartXPoint_get(swigCPtr);
      return ret;
    } 
  }

  public ConveyorTrackRangeParams() : this(nrc_interfacePINVOKE.new_ConveyorTrackRangeParams(), true) {
  }

}
