//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class DragParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DragParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DragParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DragParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DragParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_DragParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int drag_mode {
    set {
      nrc_interfacePINVOKE.DragParam_drag_mode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.DragParam_drag_mode_get(swigCPtr);
      return ret;
    } 
  }

  public double start_threshold_F {
    set {
      nrc_interfacePINVOKE.DragParam_start_threshold_F_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.DragParam_start_threshold_F_get(swigCPtr);
      return ret;
    } 
  }

  public double start_threshold_M {
    set {
      nrc_interfacePINVOKE.DragParam_start_threshold_M_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.DragParam_start_threshold_M_get(swigCPtr);
      return ret;
    } 
  }

  public double dragInPosMaxVel {
    set {
      nrc_interfacePINVOKE.DragParam_dragInPosMaxVel_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.DragParam_dragInPosMaxVel_get(swigCPtr);
      return ret;
    } 
  }

  public double dragInPosMaxAngleVel {
    set {
      nrc_interfacePINVOKE.DragParam_dragInPosMaxAngleVel_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.DragParam_dragInPosMaxAngleVel_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_double drag_change_rate {
    set {
      nrc_interfacePINVOKE.DragParam_drag_change_rate_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.DragParam_drag_change_rate_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double drag_damper {
    set {
      nrc_interfacePINVOKE.DragParam_drag_damper_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.DragParam_drag_damper_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double drag_mass {
    set {
      nrc_interfacePINVOKE.DragParam_drag_mass_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.DragParam_drag_mass_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public DragParam() : this(nrc_interfacePINVOKE.new_DragParam(), true) {
  }

}
