//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IndependentAxisRun : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IndependentAxisRun(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IndependentAxisRun obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IndependentAxisRun obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IndependentAxisRun() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_IndependentAxisRun(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int axis_num {
    set {
      nrc_interfacePINVOKE.IndependentAxisRun_axis_num_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IndependentAxisRun_axis_num_get(swigCPtr);
      return ret;
    } 
  }

  public int vel {
    set {
      nrc_interfacePINVOKE.IndependentAxisRun_vel_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IndependentAxisRun_vel_get(swigCPtr);
      return ret;
    } 
  }

  public int dir {
    set {
      nrc_interfacePINVOKE.IndependentAxisRun_dir_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IndependentAxisRun_dir_get(swigCPtr);
      return ret;
    } 
  }

  public double acc {
    set {
      nrc_interfacePINVOKE.IndependentAxisRun_acc_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisRun_acc_get(swigCPtr);
      return ret;
    } 
  }

  public double dec {
    set {
      nrc_interfacePINVOKE.IndependentAxisRun_dec_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisRun_dec_get(swigCPtr);
      return ret;
    } 
  }

  public IndependentAxisRun() : this(nrc_interfacePINVOKE.new_IndependentAxisRun(), true) {
  }

}
