//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IndependentAxisParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IndependentAxisParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IndependentAxisParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IndependentAxisParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IndependentAxisParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_IndependentAxisParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int axis_num {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_axis_num_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IndependentAxisParam_axis_num_get(swigCPtr);
      return ret;
    } 
  }

  public double angular_distance_conversion_ratio_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_angular_distance_conversion_ratio_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_angular_distance_conversion_ratio_value_get(swigCPtr);
      return ret;
    } 
  }

  public bool is_track {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_is_track_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.IndependentAxisParam_is_track_get(swigCPtr);
      return ret;
    } 
  }

  public double encoder_bit_linedit_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_encoder_bit_linedit_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_encoder_bit_linedit_value_get(swigCPtr);
      return ret;
    } 
  }

  public double inverse_limit_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_inverse_limit_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_inverse_limit_value_get(swigCPtr);
      return ret;
    } 
  }

  public double maximum_positive_speed_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_maximum_positive_speed_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_maximum_positive_speed_value_get(swigCPtr);
      return ret;
    } 
  }

  public double maximum_reverse_speed_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_maximum_reverse_speed_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_maximum_reverse_speed_value_get(swigCPtr);
      return ret;
    } 
  }

  public int motor_dir {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_motor_dir_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IndependentAxisParam_motor_dir_get(swigCPtr);
      return ret;
    } 
  }

  public double positive_limit_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_positive_limit_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_positive_limit_value_get(swigCPtr);
      return ret;
    } 
  }

  public double rated_positive_speed_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_rated_positive_speed_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_rated_positive_speed_value_get(swigCPtr);
      return ret;
    } 
  }

  public double rated_reverse_speed_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_rated_reverse_speed_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_rated_reverse_speed_value_get(swigCPtr);
      return ret;
    } 
  }

  public double reduction_ratio_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_reduction_ratio_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_reduction_ratio_value_get(swigCPtr);
      return ret;
    } 
  }

  public double max_acc_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_max_acc_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_max_acc_value_get(swigCPtr);
      return ret;
    } 
  }

  public double max_dec_value {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_max_dec_value_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.IndependentAxisParam_max_dec_value_get(swigCPtr);
      return ret;
    } 
  }

  public int select_bind_servo {
    set {
      nrc_interfacePINVOKE.IndependentAxisParam_select_bind_servo_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IndependentAxisParam_select_bind_servo_get(swigCPtr);
      return ret;
    } 
  }

  public IndependentAxisParam() : this(nrc_interfacePINVOKE.new_IndependentAxisParam(), true) {
  }

}
