//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IO : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IO(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IO obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IO obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IO() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_IO(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int AO_laserPower {
    set {
      nrc_interfacePINVOKE.IO_AO_laserPower_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_AO_laserPower_get(swigCPtr);
      return ret;
    } 
  }

  public int AO_pressure {
    set {
      nrc_interfacePINVOKE.IO_AO_pressure_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_AO_pressure_get(swigCPtr);
      return ret;
    } 
  }

  public int DI_backMiddleArrival {
    set {
      nrc_interfacePINVOKE.IO_DI_backMiddleArrival_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DI_backMiddleArrival_get(swigCPtr);
      return ret;
    } 
  }

  public int DI_capacitance_ {
    set {
      nrc_interfacePINVOKE.IO_DI_capacitance__set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DI_capacitance__get(swigCPtr);
      return ret;
    } 
  }

  public int DI_followArrival {
    set {
      nrc_interfacePINVOKE.IO_DI_followArrival_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DI_followArrival_get(swigCPtr);
      return ret;
    } 
  }

  public int DI_liftUpArrival {
    set {
      nrc_interfacePINVOKE.IO_DI_liftUpArrival_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DI_liftUpArrival_get(swigCPtr);
      return ret;
    } 
  }

  public int DI_perforateArrival {
    set {
      nrc_interfacePINVOKE.IO_DI_perforateArrival_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DI_perforateArrival_get(swigCPtr);
      return ret;
    } 
  }

  public int DO_aspiration {
    set {
      nrc_interfacePINVOKE.IO_DO_aspiration_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DO_aspiration_get(swigCPtr);
      return ret;
    } 
  }

  public int DO_backMiddle {
    set {
      nrc_interfacePINVOKE.IO_DO_backMiddle_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DO_backMiddle_get(swigCPtr);
      return ret;
    } 
  }

  public int DO_capacitance_ {
    set {
      nrc_interfacePINVOKE.IO_DO_capacitance__set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DO_capacitance__get(swigCPtr);
      return ret;
    } 
  }

  public int DO_follow {
    set {
      nrc_interfacePINVOKE.IO_DO_follow_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DO_follow_get(swigCPtr);
      return ret;
    } 
  }

  public int DO_highPressgas {
    set {
      nrc_interfacePINVOKE.IO_DO_highPressgas_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DO_highPressgas_get(swigCPtr);
      return ret;
    } 
  }

  public int DO_liftUp {
    set {
      nrc_interfacePINVOKE.IO_DO_liftUp_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DO_liftUp_get(swigCPtr);
      return ret;
    } 
  }

  public int DO_lightGate {
    set {
      nrc_interfacePINVOKE.IO_DO_lightGate_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DO_lightGate_get(swigCPtr);
      return ret;
    } 
  }

  public int DO_lowPressgas {
    set {
      nrc_interfacePINVOKE.IO_DO_lowPressgas_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DO_lowPressgas_get(swigCPtr);
      return ret;
    } 
  }

  public int DO_redLight {
    set {
      nrc_interfacePINVOKE.IO_DO_redLight_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_DO_redLight_get(swigCPtr);
      return ret;
    } 
  }

  public int pwm_port_ {
    set {
      nrc_interfacePINVOKE.IO_pwm_port__set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IO_pwm_port__get(swigCPtr);
      return ret;
    } 
  }

  public IO() : this(nrc_interfacePINVOKE.new_IO(), true) {
  }

}
