//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IOCommandParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IOCommandParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IOCommandParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IOCommandParams obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IOCommandParams() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_IOCommandParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string groupType {
    set {
      nrc_interfacePINVOKE.IOCommandParams_groupType_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.IOCommandParams_groupType_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int errorHanding {
    set {
      nrc_interfacePINVOKE.IOCommandParams_errorHanding_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.IOCommandParams_errorHanding_get(swigCPtr);
      return ret;
    } 
  }

  public ParaGroup paraGroupNum {
    set {
      nrc_interfacePINVOKE.IOCommandParams_paraGroupNum_set(swigCPtr, ParaGroup.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.IOCommandParams_paraGroupNum_get(swigCPtr);
      ParaGroup ret = (cPtr == global::System.IntPtr.Zero) ? null : new ParaGroup(cPtr, false);
      return ret;
    } 
  }

  public ParaGroup paraGroupTime {
    set {
      nrc_interfacePINVOKE.IOCommandParams_paraGroupTime_set(swigCPtr, ParaGroup.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.IOCommandParams_paraGroupTime_get(swigCPtr);
      ParaGroup ret = (cPtr == global::System.IntPtr.Zero) ? null : new ParaGroup(cPtr, false);
      return ret;
    } 
  }

  public ParaGroup paraGroupValue {
    set {
      nrc_interfacePINVOKE.IOCommandParams_paraGroupValue_set(swigCPtr, ParaGroup.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.IOCommandParams_paraGroupValue_get(swigCPtr);
      ParaGroup ret = (cPtr == global::System.IntPtr.Zero) ? null : new ParaGroup(cPtr, false);
      return ret;
    } 
  }

  public IOCommandParams() : this(nrc_interfacePINVOKE.new_IOCommandParams(), true) {
  }

}
