//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LaserCuttingIOParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaserCuttingIOParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaserCuttingIOParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaserCuttingIOParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LaserCuttingIOParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_LaserCuttingIOParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IO io {
    set {
      nrc_interfacePINVOKE.LaserCuttingIOParam_io_set(swigCPtr, IO.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.LaserCuttingIOParam_io_get(swigCPtr);
      IO ret = (cPtr == global::System.IntPtr.Zero) ? null : new IO(cPtr, false);
      return ret;
    } 
  }

  public Fault laser_fault {
    set {
      nrc_interfacePINVOKE.LaserCuttingIOParam_laser_fault_set(swigCPtr, Fault.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.LaserCuttingIOParam_laser_fault_get(swigCPtr);
      Fault ret = (cPtr == global::System.IntPtr.Zero) ? null : new Fault(cPtr, false);
      return ret;
    } 
  }

  public Fault pressure_fault {
    set {
      nrc_interfacePINVOKE.LaserCuttingIOParam_pressure_fault_set(swigCPtr, Fault.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.LaserCuttingIOParam_pressure_fault_get(swigCPtr);
      Fault ret = (cPtr == global::System.IntPtr.Zero) ? null : new Fault(cPtr, false);
      return ret;
    } 
  }

  public Fault regulator_fault {
    set {
      nrc_interfacePINVOKE.LaserCuttingIOParam_regulator_fault_set(swigCPtr, Fault.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.LaserCuttingIOParam_regulator_fault_get(swigCPtr);
      Fault ret = (cPtr == global::System.IntPtr.Zero) ? null : new Fault(cPtr, false);
      return ret;
    } 
  }

  public Fault water_cooler_fault {
    set {
      nrc_interfacePINVOKE.LaserCuttingIOParam_water_cooler_fault_set(swigCPtr, Fault.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.LaserCuttingIOParam_water_cooler_fault_get(swigCPtr);
      Fault ret = (cPtr == global::System.IntPtr.Zero) ? null : new Fault(cPtr, false);
      return ret;
    } 
  }

  public LaserCuttingIOParam() : this(nrc_interfacePINVOKE.new_LaserCuttingIOParam(), true) {
  }

}
