//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LaserCuttingEquipment : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaserCuttingEquipment(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaserCuttingEquipment obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaserCuttingEquipment obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LaserCuttingEquipment() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_LaserCuttingEquipment(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double RetreatDistance {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_RetreatDistance_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingEquipment_RetreatDistance_get(swigCPtr);
      return ret;
    } 
  }

  public int arrivalOutLightMode {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_arrivalOutLightMode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.LaserCuttingEquipment_arrivalOutLightMode_get(swigCPtr);
      return ret;
    } 
  }

  public double collisionDistance {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_collisionDistance_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingEquipment_collisionDistance_get(swigCPtr);
      return ret;
    } 
  }

  public int delAspiratedMode {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_delAspiratedMode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.LaserCuttingEquipment_delAspiratedMode_get(swigCPtr);
      return ret;
    } 
  }

  public double delAspiratedTime {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_delAspiratedTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingEquipment_delAspiratedTime_get(swigCPtr);
      return ret;
    } 
  }

  public bool focusCompensation {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_focusCompensation_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.LaserCuttingEquipment_focusCompensation_get(swigCPtr);
      return ret;
    } 
  }

  public double focusCompensationConstant {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_focusCompensationConstant_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingEquipment_focusCompensationConstant_get(swigCPtr);
      return ret;
    } 
  }

  public double focusCompensationPower {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_focusCompensationPower_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingEquipment_focusCompensationPower_get(swigCPtr);
      return ret;
    } 
  }

  public double focusCompensationTime {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_focusCompensationTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingEquipment_focusCompensationTime_get(swigCPtr);
      return ret;
    } 
  }

  public int focusFormula {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_focusFormula_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.LaserCuttingEquipment_focusFormula_get(swigCPtr);
      return ret;
    } 
  }

  public int follow {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_follow_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.LaserCuttingEquipment_follow_get(swigCPtr);
      return ret;
    } 
  }

  public double preAspiratedTime {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_preAspiratedTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingEquipment_preAspiratedTime_get(swigCPtr);
      return ret;
    } 
  }

  public int rePerforate {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_rePerforate_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.LaserCuttingEquipment_rePerforate_get(swigCPtr);
      return ret;
    } 
  }

  public double waitFollowTime {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_waitFollowTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingEquipment_waitFollowTime_get(swigCPtr);
      return ret;
    } 
  }

  public double waitLiftUpTime {
    set {
      nrc_interfacePINVOKE.LaserCuttingEquipment_waitLiftUpTime_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingEquipment_waitLiftUpTime_get(swigCPtr);
      return ret;
    } 
  }

  public LaserCuttingEquipment() : this(nrc_interfacePINVOKE.new_LaserCuttingEquipment(), true) {
  }

}
