//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LaserCuttingAnalogMatch : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaserCuttingAnalogMatch(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaserCuttingAnalogMatch obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaserCuttingAnalogMatch obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LaserCuttingAnalogMatch() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_LaserCuttingAnalogMatch(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Curve laserPower {
    set {
      nrc_interfacePINVOKE.LaserCuttingAnalogMatch_laserPower_set(swigCPtr, Curve.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.LaserCuttingAnalogMatch_laserPower_get(swigCPtr);
      Curve ret = (cPtr == global::System.IntPtr.Zero) ? null : new Curve(cPtr, false);
      return ret;
    } 
  }

  public Curve pressure {
    set {
      nrc_interfacePINVOKE.LaserCuttingAnalogMatch_pressure_set(swigCPtr, Curve.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.LaserCuttingAnalogMatch_pressure_get(swigCPtr);
      Curve ret = (cPtr == global::System.IntPtr.Zero) ? null : new Curve(cPtr, false);
      return ret;
    } 
  }

  public LaserCuttingAnalogMatch() : this(nrc_interfacePINVOKE.new_LaserCuttingAnalogMatch(), true) {
  }

}
