//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LaserCuttingParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaserCuttingParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaserCuttingParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaserCuttingParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LaserCuttingParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_LaserCuttingParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int dutyRatio {
    set {
      nrc_interfacePINVOKE.LaserCuttingParam_dutyRatio_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.LaserCuttingParam_dutyRatio_get(swigCPtr);
      return ret;
    } 
  }

  public double focusPosition {
    set {
      nrc_interfacePINVOKE.LaserCuttingParam_focusPosition_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingParam_focusPosition_get(swigCPtr);
      return ret;
    } 
  }

  public double followHeight {
    set {
      nrc_interfacePINVOKE.LaserCuttingParam_followHeight_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingParam_followHeight_get(swigCPtr);
      return ret;
    } 
  }

  public int freq {
    set {
      nrc_interfacePINVOKE.LaserCuttingParam_freq_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.LaserCuttingParam_freq_get(swigCPtr);
      return ret;
    } 
  }

  public int power {
    set {
      nrc_interfacePINVOKE.LaserCuttingParam_power_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.LaserCuttingParam_power_get(swigCPtr);
      return ret;
    } 
  }

  public double pressure {
    set {
      nrc_interfacePINVOKE.LaserCuttingParam_pressure_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.LaserCuttingParam_pressure_get(swigCPtr);
      return ret;
    } 
  }

  public string note {
    set {
      nrc_interfacePINVOKE.LaserCuttingParam_note_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.LaserCuttingParam_note_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public LaserCuttingParam() : this(nrc_interfacePINVOKE.new_LaserCuttingParam(), true) {
  }

}
