//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ModbusMasterParameter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ModbusMasterParameter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ModbusMasterParameter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ModbusMasterParameter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ModbusMasterParameter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ModbusMasterParameter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string type {
    set {
      nrc_interfacePINVOKE.ModbusMasterParameter_type_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.ModbusMasterParameter_type_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool startAddress {
    set {
      nrc_interfacePINVOKE.ModbusMasterParameter_startAddress_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.ModbusMasterParameter_startAddress_get(swigCPtr);
      return ret;
    } 
  }

  public ModbusTCPParameter TCP {
    set {
      nrc_interfacePINVOKE.ModbusMasterParameter_TCP_set(swigCPtr, ModbusTCPParameter.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.ModbusMasterParameter_TCP_get(swigCPtr);
      ModbusTCPParameter ret = (cPtr == global::System.IntPtr.Zero) ? null : new ModbusTCPParameter(cPtr, false);
      return ret;
    } 
  }

  public ModbusRTUParameter RTU {
    set {
      nrc_interfacePINVOKE.ModbusMasterParameter_RTU_set(swigCPtr, ModbusRTUParameter.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.ModbusMasterParameter_RTU_get(swigCPtr);
      ModbusRTUParameter ret = (cPtr == global::System.IntPtr.Zero) ? null : new ModbusRTUParameter(cPtr, false);
      return ret;
    } 
  }

  public ModbusMasterParameter() : this(nrc_interfacePINVOKE.new_ModbusMasterParameter(), true) {
  }

}
