//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MoveCmd : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MoveCmd(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MoveCmd obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MoveCmd obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MoveCmd() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_MoveCmd(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PosType targetPosType {
    set {
      nrc_interfacePINVOKE.MoveCmd_targetPosType_set(swigCPtr, (int)value);
    } 
    get {
      PosType ret = (PosType)nrc_interfacePINVOKE.MoveCmd_targetPosType_get(swigCPtr);
      return ret;
    } 
  }

  public VectorDouble targetPosValue {
    set {
      nrc_interfacePINVOKE.MoveCmd_targetPosValue_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.MoveCmd_targetPosValue_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public string targetPosName {
    set {
      nrc_interfacePINVOKE.MoveCmd_targetPosName_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.MoveCmd_targetPosName_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int coord {
    set {
      nrc_interfacePINVOKE.MoveCmd_coord_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.MoveCmd_coord_get(swigCPtr);
      return ret;
    } 
  }

  public double velocity {
    set {
      nrc_interfacePINVOKE.MoveCmd_velocity_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.MoveCmd_velocity_get(swigCPtr);
      return ret;
    } 
  }

  public double velocitySync {
    set {
      nrc_interfacePINVOKE.MoveCmd_velocitySync_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.MoveCmd_velocitySync_get(swigCPtr);
      return ret;
    } 
  }

  public double acc {
    set {
      nrc_interfacePINVOKE.MoveCmd_acc_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.MoveCmd_acc_get(swigCPtr);
      return ret;
    } 
  }

  public double dec {
    set {
      nrc_interfacePINVOKE.MoveCmd_dec_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.MoveCmd_dec_get(swigCPtr);
      return ret;
    } 
  }

  public int pl {
    set {
      nrc_interfacePINVOKE.MoveCmd_pl_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.MoveCmd_pl_get(swigCPtr);
      return ret;
    } 
  }

  public int time {
    set {
      nrc_interfacePINVOKE.MoveCmd_time_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.MoveCmd_time_get(swigCPtr);
      return ret;
    } 
  }

  public int toolNum {
    set {
      nrc_interfacePINVOKE.MoveCmd_toolNum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.MoveCmd_toolNum_get(swigCPtr);
      return ret;
    } 
  }

  public int userNum {
    set {
      nrc_interfacePINVOKE.MoveCmd_userNum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.MoveCmd_userNum_get(swigCPtr);
      return ret;
    } 
  }

  public int posidtype {
    set {
      nrc_interfacePINVOKE.MoveCmd_posidtype_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.MoveCmd_posidtype_get(swigCPtr);
      return ret;
    } 
  }

  public int configuration {
    set {
      nrc_interfacePINVOKE.MoveCmd_configuration_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.MoveCmd_configuration_get(swigCPtr);
      return ret;
    } 
  }

  public int spin {
    set {
      nrc_interfacePINVOKE.MoveCmd_spin_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.MoveCmd_spin_get(swigCPtr);
      return ret;
    } 
  }

  public bool parasync {
    set {
      nrc_interfacePINVOKE.MoveCmd_parasync_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.MoveCmd_parasync_get(swigCPtr);
      return ret;
    } 
  }

  public MoveCmd() : this(nrc_interfacePINVOKE.new_MoveCmd(), true) {
  }

}
