//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Position : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Position(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Position obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Position obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Position() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_Position(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int angleDirection {
    set {
      nrc_interfacePINVOKE.Position_angleDirection_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Position_angleDirection_get(swigCPtr);
      return ret;
    } 
  }

  public string cameraData {
    set {
      nrc_interfacePINVOKE.Position_cameraData_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Position_cameraData_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VectorDouble cameraPoint {
    set {
      nrc_interfacePINVOKE.Position_cameraPoint_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.Position_cameraPoint_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public VectorDouble datumPoint {
    set {
      nrc_interfacePINVOKE.Position_datumPoint_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.Position_datumPoint_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public VectorDouble datumPointDeg {
    set {
      nrc_interfacePINVOKE.Position_datumPointDeg_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.Position_datumPointDeg_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public Excursion excursion {
    set {
      nrc_interfacePINVOKE.Position_excursion_set(swigCPtr, Excursion.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.Position_excursion_get(swigCPtr);
      Excursion ret = (cPtr == global::System.IntPtr.Zero) ? null : new Excursion(cPtr, false);
      return ret;
    } 
  }

  public int recvPointsType {
    set {
      nrc_interfacePINVOKE.Position_recvPointsType_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Position_recvPointsType_get(swigCPtr);
      return ret;
    } 
  }

  public string sampleData {
    set {
      nrc_interfacePINVOKE.Position_sampleData_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Position_sampleData_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double scale {
    set {
      nrc_interfacePINVOKE.Position_scale_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.Position_scale_get(swigCPtr);
      return ret;
    } 
  }

  public Position() : this(nrc_interfacePINVOKE.new_Position(), true) {
  }

}
