//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PositionData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PositionData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PositionData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PositionData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PositionData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_PositionData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string key {
    set {
      nrc_interfacePINVOKE.PositionData_key_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.PositionData_key_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VectorDouble posData {
    set {
      nrc_interfacePINVOKE.PositionData_posData_set(swigCPtr, VectorDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.PositionData_posData_get(swigCPtr);
      VectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDouble(cPtr, false);
      return ret;
    } 
  }

  public int coord {
    set {
      nrc_interfacePINVOKE.PositionData_coord_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.PositionData_coord_get(swigCPtr);
      return ret;
    } 
  }

  public int toolNum {
    set {
      nrc_interfacePINVOKE.PositionData_toolNum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.PositionData_toolNum_get(swigCPtr);
      return ret;
    } 
  }

  public int userNum {
    set {
      nrc_interfacePINVOKE.PositionData_userNum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.PositionData_userNum_get(swigCPtr);
      return ret;
    } 
  }

  public PosType type {
    set {
      nrc_interfacePINVOKE.PositionData_type_set(swigCPtr, (int)value);
    } 
    get {
      PosType ret = (PosType)nrc_interfacePINVOKE.PositionData_type_get(swigCPtr);
      return ret;
    } 
  }

  public static PosType determineType(string key) {
    PosType ret = (PosType)nrc_interfacePINVOKE.PositionData_determineType(key);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PositionData() : this(nrc_interfacePINVOKE.new_PositionData(), true) {
  }

}
