//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Protocol : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Protocol(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Protocol obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Protocol obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Protocol() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_Protocol(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string addDataInitialPara {
    set {
      nrc_interfacePINVOKE.Protocol_addDataInitialPara_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Protocol_addDataInitialPara_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int addDataNum {
    set {
      nrc_interfacePINVOKE.Protocol_addDataNum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Protocol_addDataNum_get(swigCPtr);
      return ret;
    } 
  }

  public int angleUnit {
    set {
      nrc_interfacePINVOKE.Protocol_angleUnit_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Protocol_angleUnit_get(swigCPtr);
      return ret;
    } 
  }

  public string endMark {
    set {
      nrc_interfacePINVOKE.Protocol_endMark_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Protocol_endMark_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string failFlag {
    set {
      nrc_interfacePINVOKE.Protocol_failFlag_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Protocol_failFlag_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string frameHeader {
    set {
      nrc_interfacePINVOKE.Protocol_frameHeader_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Protocol_frameHeader_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool hasTCS {
    set {
      nrc_interfacePINVOKE.Protocol_hasTCS_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.Protocol_hasTCS_get(swigCPtr);
      return ret;
    } 
  }

  public bool hasUCS {
    set {
      nrc_interfacePINVOKE.Protocol_hasUCS_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.Protocol_hasUCS_get(swigCPtr);
      return ret;
    } 
  }

  public string separator {
    set {
      nrc_interfacePINVOKE.Protocol_separator_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Protocol_separator_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool singleTarget {
    set {
      nrc_interfacePINVOKE.Protocol_singleTarget_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.Protocol_singleTarget_get(swigCPtr);
      return ret;
    } 
  }

  public string successFlag {
    set {
      nrc_interfacePINVOKE.Protocol_successFlag_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Protocol_successFlag_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int timeOut {
    set {
      nrc_interfacePINVOKE.Protocol_timeOut_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Protocol_timeOut_get(swigCPtr);
      return ret;
    } 
  }

  public int type {
    set {
      nrc_interfacePINVOKE.Protocol_type_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Protocol_type_get(swigCPtr);
      return ret;
    } 
  }

  public Protocol() : this(nrc_interfacePINVOKE.new_Protocol(), true) {
  }

}
