//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ToolParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ToolParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ToolParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ToolParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ToolParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_ToolParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double X {
    set {
      nrc_interfacePINVOKE.ToolParam_X_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_X_get(swigCPtr);
      return ret;
    } 
  }

  public double Y {
    set {
      nrc_interfacePINVOKE.ToolParam_Y_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_Y_get(swigCPtr);
      return ret;
    } 
  }

  public double Z {
    set {
      nrc_interfacePINVOKE.ToolParam_Z_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_Z_get(swigCPtr);
      return ret;
    } 
  }

  public double A {
    set {
      nrc_interfacePINVOKE.ToolParam_A_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_A_get(swigCPtr);
      return ret;
    } 
  }

  public double B {
    set {
      nrc_interfacePINVOKE.ToolParam_B_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_B_get(swigCPtr);
      return ret;
    } 
  }

  public double C {
    set {
      nrc_interfacePINVOKE.ToolParam_C_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_C_get(swigCPtr);
      return ret;
    } 
  }

  public double payloadMass {
    set {
      nrc_interfacePINVOKE.ToolParam_payloadMass_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_payloadMass_get(swigCPtr);
      return ret;
    } 
  }

  public double payloadInertia {
    set {
      nrc_interfacePINVOKE.ToolParam_payloadInertia_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_payloadInertia_get(swigCPtr);
      return ret;
    } 
  }

  public double payloadMassCenter_X {
    set {
      nrc_interfacePINVOKE.ToolParam_payloadMassCenter_X_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_payloadMassCenter_X_get(swigCPtr);
      return ret;
    } 
  }

  public double payloadMassCenter_Y {
    set {
      nrc_interfacePINVOKE.ToolParam_payloadMassCenter_Y_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_payloadMassCenter_Y_get(swigCPtr);
      return ret;
    } 
  }

  public double payloadMassCenter_Z {
    set {
      nrc_interfacePINVOKE.ToolParam_payloadMassCenter_Z_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.ToolParam_payloadMassCenter_Z_get(swigCPtr);
      return ret;
    } 
  }

  public ToolParam() : this(nrc_interfacePINVOKE.new_ToolParam(), true) {
  }

}
