//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Trigger : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Trigger(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Trigger obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Trigger obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Trigger() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_Trigger(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int IOPort {
    set {
      nrc_interfacePINVOKE.Trigger_IOPort_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Trigger_IOPort_get(swigCPtr);
      return ret;
    } 
  }

  public int duration {
    set {
      nrc_interfacePINVOKE.Trigger_duration_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Trigger_duration_get(swigCPtr);
      return ret;
    } 
  }

  public int intervals {
    set {
      nrc_interfacePINVOKE.Trigger_intervals_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Trigger_intervals_get(swigCPtr);
      return ret;
    } 
  }

  public int triggerMode {
    set {
      nrc_interfacePINVOKE.Trigger_triggerMode_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.Trigger_triggerMode_get(swigCPtr);
      return ret;
    } 
  }

  public bool triggerOnce {
    set {
      nrc_interfacePINVOKE.Trigger_triggerOnce_set(swigCPtr, value);
    } 
    get {
      bool ret = nrc_interfacePINVOKE.Trigger_triggerOnce_get(swigCPtr);
      return ret;
    } 
  }

  public string triggerStr {
    set {
      nrc_interfacePINVOKE.Trigger_triggerStr_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.Trigger_triggerStr_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Trigger() : this(nrc_interfacePINVOKE.new_Trigger(), true) {
  }

}
