//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VFDState : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VFDState(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VFDState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VFDState obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VFDState() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VFDState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int motor_vel {
    set {
      nrc_interfacePINVOKE.VFDState_motor_vel_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.VFDState_motor_vel_get(swigCPtr);
      return ret;
    } 
  }

  public int motor_current {
    set {
      nrc_interfacePINVOKE.VFDState_motor_current_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.VFDState_motor_current_get(swigCPtr);
      return ret;
    } 
  }

  public double spindle_angle {
    set {
      nrc_interfacePINVOKE.VFDState_spindle_angle_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.VFDState_spindle_angle_get(swigCPtr);
      return ret;
    } 
  }

  public VFDState() : this(nrc_interfacePINVOKE.new_VFDState(), true) {
  }

}
