//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VisionParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VisionParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VisionParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VisionParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VisionParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VisionParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CameraList cameraList {
    set {
      nrc_interfacePINVOKE.VisionParam_cameraList_set(swigCPtr, CameraList.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionParam_cameraList_get(swigCPtr);
      CameraList ret = (cPtr == global::System.IntPtr.Zero) ? null : new CameraList(cPtr, false);
      return ret;
    } 
  }

  public Protocol protocol {
    set {
      nrc_interfacePINVOKE.VisionParam_protocol_set(swigCPtr, Protocol.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionParam_protocol_get(swigCPtr);
      Protocol ret = (cPtr == global::System.IntPtr.Zero) ? null : new Protocol(cPtr, false);
      return ret;
    } 
  }

  public Socket socket {
    set {
      nrc_interfacePINVOKE.VisionParam_socket_set(swigCPtr, Socket.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionParam_socket_get(swigCPtr);
      Socket ret = (cPtr == global::System.IntPtr.Zero) ? null : new Socket(cPtr, false);
      return ret;
    } 
  }

  public Trigger trigger {
    set {
      nrc_interfacePINVOKE.VisionParam_trigger_set(swigCPtr, Trigger.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionParam_trigger_get(swigCPtr);
      Trigger ret = (cPtr == global::System.IntPtr.Zero) ? null : new Trigger(cPtr, false);
      return ret;
    } 
  }

  public int userCoordNum {
    set {
      nrc_interfacePINVOKE.VisionParam_userCoordNum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.VisionParam_userCoordNum_get(swigCPtr);
      return ret;
    } 
  }

  public VisionParam() : this(nrc_interfacePINVOKE.new_VisionParam(), true) {
  }

}
