//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VisionRange : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VisionRange(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VisionRange obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VisionRange obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VisionRange() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VisionRange(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string maxX {
    set {
      nrc_interfacePINVOKE.VisionRange_maxX_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.VisionRange_maxX_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string maxY {
    set {
      nrc_interfacePINVOKE.VisionRange_maxY_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.VisionRange_maxY_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string maxZ {
    set {
      nrc_interfacePINVOKE.VisionRange_maxZ_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.VisionRange_maxZ_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string minX {
    set {
      nrc_interfacePINVOKE.VisionRange_minX_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.VisionRange_minX_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string minY {
    set {
      nrc_interfacePINVOKE.VisionRange_minY_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.VisionRange_minY_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string minZ {
    set {
      nrc_interfacePINVOKE.VisionRange_minZ_set(swigCPtr, value);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = nrc_interfacePINVOKE.VisionRange_minZ_get(swigCPtr);
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VisionRange() : this(nrc_interfacePINVOKE.new_VisionRange(), true) {
  }

}
